alter table FINANCE_OPERATION add constraint FK_FINANCE_OPERATION_ON_ACCOUNT foreign key (ACCOUNT_ID) references FINANCE_ACCOUNT(ID);
create index IDX_FINANCE_OPERATION_ON_ACCOUNT on FINANCE_OPERATION (ACCOUNT_ID);
